"""New Migration5

Revision ID: 0fc882c61e2f
Revises: bbdbbe63dae7
Create Date: 2023-01-16 13:29:03.251491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0fc882c61e2f"
down_revision = "bbdbbe63dae7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dishes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("pries", sa.Float(), nullable=True),
        sa.Column("submenu_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["submenu_id"], ["submenu.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dishes_id"), "dishes", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dishes_id"), table_name="dishes")
    op.drop_table("dishes")
    # ### end Alembic commands ###
