"""New Migration1

Revision ID: 2d16e2bc74a4
Revises: e541c9ad8df8
Create Date: 2023-01-15 20:01:41.463032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2d16e2bc74a4"
down_revision = "e541c9ad8df8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_menu_id"), "menu", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_menu_id"), table_name="menu")
    op.drop_table("menu")
    # ### end Alembic commands ###
