"""New Migration6

Revision ID: 989f25a5a815
Revises: 0fc882c61e2f
Create Date: 2023-01-16 13:45:13.953357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "989f25a5a815"
down_revision = "0fc882c61e2f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
