"""New Migration3

Revision ID: a4595c033d84
Revises: 2d16e2bc74a4
Create Date: 2023-01-15 21:22:13.871863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a4595c033d84"
down_revision = "2d16e2bc74a4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "submenu",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("menu", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["menu"], ["menu.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_submenu_id"), "submenu", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_submenu_id"), table_name="submenu")
    op.drop_table("submenu")
    # ### end Alembic commands ###
