"""New Migration4

Revision ID: bbdbbe63dae7
Revises: a4595c033d84
Create Date: 2023-01-15 21:48:44.024185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bbdbbe63dae7"
down_revision = "a4595c033d84"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
