"""New Migration

Revision ID: e541c9ad8df8
Revises: 
Create Date: 2023-01-15 19:59:40.867776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e541c9ad8df8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
